// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gulysdbrpzrfcvsaaare.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bHlzZGJycHpyZmN2c2FhYXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NzI0ODMsImV4cCI6MjA3MDM0ODQ4M30.OXntFPPdRaxSD29_e9WwkPINjgoAWNJgNlOHSWV5UkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});